### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by djones06**
cause I'm at werk. It does the stuff when I run the js script in the Chrome console. 

- badgerz

### CODE REVIEW

**Comment by I-Dont-Remember** [comment]
Did you try loading it as the extension or just running from console?  We probably gotta wait for the DOM to load before having it walk

**Comment by I-Dont-Remember** [comment]
Oh maybe not, cloud to butt didn't https://github.com/panicsteve/cloud-to-butt/blob/master/Source/content_script.js

**Comment by djones06** [comment]
Just using the console cause I can't install other chrome extensions at work

**Comment by I-Dont-Remember** [comment]
Yolo, merging this

**Pull request merged**
